### ISSUE TITLE
sent_message.py 报错

### ISSUE THREAD

**Issue by ourbest** [youfou/wxpy#101]
>   File "/usr/local/lib/python3.6/site-packages/wxpy/api/messages/sent_message.py", line 88, in member
>     if isinstance(Group, self.receiver):

```
    @property
    def member(self):
        """
        若在群聊中发送消息，则为群员
        """
        from wxpy import Group

        if isinstance(Group, self.receiver):
            return self.receiver.self
```

这个isinstance是不是参数搞反了

**Comment by youfou** [comment]
我错了 😂
已 merge，感谢！
