### ISSUE TITLE
群聊中search按地区性别查找都返回空数组

### ISSUE THREAD

**Issue by honwenle** [youfou/wxpy#113]
对单个Group的members执行.search(sex=MALE)之类的查询都是返回空数组，但是name查询有效。
包括stats_text()和stats等统计方法也都返回空

**Comment by honwenle** [comment]
应该是Member对象只有name属性可以访问，其他User类属性都返回空

**Comment by mapleflow** [comment]
检查下原始数据 raw 看看，有时候程序封装的不对

**Comment by honwenle** [comment]
是的，输出了单个Member的raw看了一下，确实没有性别地区那些属性
`{'Uin': 0, 'UserName': '@3f92188db1acb0a1d317649f306dc42c2d2a90b5acd0b328b1ab70351bc83922', 'RemarkPYInitial': '', 'NickName': '扣紫链', 'RemarkPYQuanPin': '', 'AttrStatus': 100543, 'KeyWord': '', 'DisplayName
': '', 'PYInitial': '', 'PYQuanPin': '', 'MemberStatus': 0}`

**Comment by JonathanStrangeHelium** [comment]
@honwenle 
默认不获取省市性别等信息的。需要开启：
`group.update_group(True)`

**Comment by honwenle** [comment]
@0xff007 谢谢你，就是这个原因
