### ISSUE TITLE
how to get the avatar url

### ISSUE THREAD

**Issue by csrgxtu** [youfou/wxpy#12]
```python
friend = bot.friends()[6]  
friend.get_avatar(save_path='/tmp/f.jpg')
```
the upper code will save the avatar to the filesystem, but i just want the url weixin server returned, how can i get it?

**Comment by youfou** [comment]
the avatar url may be updated when the account session changes.
what's the point to get the url for?
if you prefer the image data to the real file, just left the `save_path` arg as `None`.
