### ISSUE TITLE
远程连接AWS，二维码无法显示

### ISSUE THREAD

**Issue by evestorm** [youfou/wxpy#124]
Traceback (most recent call last):
  File "getpuid.py", line 5, in <module>
    bot = Bot(cache_path=True)
  File "/home/ec2-user/wxpy/wxpy/api/bot.py", line 90, in __init__
    raise Exception('use `console_qr` arg while under pure console environment')
Exception: use `console_qr` arg while under pure console environment

这种问题怎么解决呢？没有查到相关方案...

**Comment by aaronliruns** [comment]
bot = Bot(None,2,None,None,None,None)

**Comment by evestorm** [comment]
@aaronliruns  Thx
