### ISSUE TITLE
如何获取自己手机给别人发的消息呢

### ISSUE THREAD

**Issue by a471640241** [youfou/wxpy#15]

**Comment by youfou** [comment]
请看文档
http://wxpy.readthedocs.io/zh/latest/messages.html#wxpy.Bot.register

将 `except_self` 参数设为 False，就可以注册到自己在手机上发送的消息

**Comment by a471640241** [comment]
多谢，之前没找到

**Comment by youfou** [comment]
@a471640241 

Hello，

可以获得您的联系方式吗？
或者，可以的话，能否加一下我的微信ID: youfou ？

谢谢。

**Comment by a471640241** [comment]
@youfou QQ 471640241
