### ISSUE TITLE
[建议]建议增加消息尾巴选项

### ISSUE THREAD

**Issue by Levstyle** [youfou/wxpy#16]
## 有时候想注明消息是由机器人发出来的，避免机器人造成不必要的误解，希望大神能增加一个可选参数，定义消息的尾巴。。。。。。。

**Comment by youfou** [comment]
可以使用 tuling.reply_text(msg) 仅获得回复文本，而不直接发送
然后自行修改文本，再发送出去。

**Comment by Levstyle** [comment]
这样啊，谢谢啊，哇。。。
