### ISSUE TITLE
部分消息的 .text 为 None

### ISSUE THREAD

**Issue by zjuguxi** [youfou/wxpy#17]
Traceback (most recent call last):
  File "/path/lib/python3.5/site-packages/wxpy/api/bot.py", line 295, in process
    ret = config.func(msg)
  File "wxbot.py", line 23, in reply_pt_kill
    if 'pt' in msg.text and 'kill' in msg.text:
TypeError: argument of type 'NoneType' is not iterable

**Comment by youfou** [comment]
试试过滤下消息类型？有些消息类型的 .text 确实是 None

建议的做法是，注册时过滤消息类型，比如

```python
@bot.register(bot.self, TEXT, except_self=False)
def reply_pt_kill(msg):
    ...
```

**Comment by zjuguxi** [comment]
我是自己给自己发的纯文本，这种特殊情况下的纯文本消息类型和普通的纯文本不同吗？

**Comment by youfou** [comment]
只要是TEXT类型的消息，msg.text 就一定是字符串呢，而且不会为空。
我刚刚测试了自己给自己发送纯文本，msg.text 不会为 None。

能否提供下问题的必现路径？

**Comment by youfou** [comment]
Hello @zjuguxi ， 问题解决了吗？
