### ISSUE TITLE
如何等待用户回信

### ISSUE THREAD

**Issue by w93163red** [youfou/wxpy#177]
我现在在做一个类似游戏的东西（自嗨用）。。需要等待用户的输入来驱动游戏的进程。。但是现在提供的阻塞函数如果使用了。。就不能关闭阻塞了（除了把线程终结掉，这样写对于我的需求来说太麻烦了），有没有提供什么接口会自动类似await and receive msg的？

**Comment by onestone1879** [comment]
两个思路：
1、itchat/core中的get_msg可以实现这个功能
    def get_msg(self):
        ''' fetch messages
            for fetching
                - method blocks for sometime util
                    - new messages are to be received
                    - or anytime they like
                - synckey is updated with returned synccheckkey
            it is defined in components/login.py
        '''
2、用一个MQ中间件

**Comment by w93163red** [comment]
get_msg直接跳过去了。。如果机器人发消息也算在msg里吧（get_msg也会获取？）

**Comment by w93163red** [comment]
我自己想了一个办法解决了。。
如果bot.messages的长度发生变化了 那就证明收到消息了。
