### ISSUE TITLE
自己发给自己消息后 return 抛出异常

### ISSUE THREAD

**Issue by a471640241** [youfou/wxpy#18]
自己发给自己消息后，想再给自己一个反馈直接return 后抛出下面异常
> wxpy.exceptions.ResponseError: ret: 1204; err_msg:

**Comment by youfou** [comment]
这个异常是由微信服务端返回的。
能否试试在Web微信 wx.qq.com 上面进行相同的操作，看是否能够成功？
如果Web微信上没有问题，啊麻烦贴出出现问题的代码，及 traceback，谢谢。

**Comment by a471640241** [comment]
@youfou 
真的是中大奖了，我的小号不能给自己发消息，大号可以，我之前看itcaht的时候就有看到说有些号天生不能发，我在web端试了 确实发布出去，
