### ISSUE TITLE
如何判断当前群已经满员？

### ISSUE THREAD

**Issue by NxDon** [youfou/wxpy#187]
我要实现一个自动加群的功能，比如说大家都在群1，当加满500人后，我通过什么去判断这个群人数已经满员呢

**Comment by heqiuzhi** [comment]
可以实时查询群成员的数量呀.
http://wxpy.readthedocs.io/zh/latest/_modules/wxpy/api/chats/group.html?highlight=group

**Comment by NxDon** [comment]
明白了，谢谢
