### ISSUE TITLE
消息不知道突然乱发了

### ISSUE THREAD

**Issue by a471640241** [youfou/wxpy#19]
今天进到服务器里看了一下，发现控制台没反应，我按了几次回车之后，消息突然乱发了，本来只有个人聊天的监听返回的消息发到群里，公众号里，只发了最近的几个有使用的。不知道是什么原因，我重启了服务，后面如果有的话我把报错的发出来。

**Comment by youfou** [comment]
请试试更新wxpy版本到最新的0.3.1
先前有发现一个比较特别的BUG，当注册时传入空列表导致匹配所有聊天对象的问题，在最新版本中修复了。

**Comment by a471640241** [comment]
已经是0.3.1版了，确实是空列表时直接return 消息 会发给部分人。

**Comment by youfou** [comment]
现在这个问题还存在吗？

**Comment by a471640241** [comment]
还在观察，之前只发生了一次。

**Comment by youfou** [comment]
好的，照理说 0.3.1 之后就应解决了这个问题
