### ISSUE TITLE
TERM environment variable not set.

### ISSUE THREAD

**Issue by ideago** [youfou/wxpy#2]
扫描二维码登录之后，调用调用发送消息接口，然后出来如标题的错误信息，截图如下，求指导。

![qq20170302-0](https://cloud.githubusercontent.com/assets/7457605/23501568/4ff6f008-ff6f-11e6-9b60-b803eba869a2.png)

**Comment by youfou** [comment]
Google下这句警告……这个警告来自于系统，而非Python或wxpy模块…
一些帖子说，设置下TERM变量就可以，试试？

```shell
export TERM=xterm
```

**Comment by youfou** [comment]
对了，可以加下项目主页中的微信群哈，很多大神在里面

**Comment by ideago** [comment]
好吧 我试试看 关键是这个警告会导致后面的调用操作无效……😞


发自网易邮箱大师
在2017年03月02日 17:50，Youfou 写道：

Google下这句警告……这个警告来自于系统，而非Python或wxpy模块…
一些帖子说，设置下TERM变量就可以，试试？

export TERM=xterm

**Comment by ideago** [comment]
嗯 加了呢 但是一直木有反应哇 我的微信号是yexuehan63 要不你帮我手动加一下……🙈


发自网易邮箱大师
在2017年03月02日 17:52，Youfou 写道：

对了，可以加下项目主页中的微信群哈，很多大神在里面

**Comment by youfou** [comment]
已经发了群邀请了，注意确认。
我也不懂这个，可以问问群里的大神们哈。
