### ISSUE TITLE
如何获取群成员 member 的地区信息？

### ISSUE THREAD

**Issue by justacli** [youfou/wxpy#200]

**Comment by mapleflow** [comment]
http://wxpy.readthedocs.io/zh/latest/chats.html?highlight=%E5%9C%B0%E5%8C%BA#wxpy.User

**Comment by davidaclee** [comment]
@mapleflow 嗯，我有看到这个，User(raw, bot) 里的两个参数应该分别填写什么呢？

**Comment by justacli** [comment]
@mapleflow Member 的 raw 信息没有 province 和 city 字段

**Comment by feifanhanmc** [comment]
your_group.update_group(members_details=True);
然后就可以看到包括地区信息的member的完备信息了。
