### ISSUE TITLE
监听不到群消息

### ISSUE THREAD

**Issue by dev-emmon** [youfou/wxpy#208]
>>> @bot.register(Group)
... def print_group_msg(msg):
...     print(msg)
...
>>>

设置了监听，并打印群消息后
用其它号在群里发消息无法收到

**Comment by onestone1879** [comment]
缩进？

**Comment by dev-emmon** [comment]
缩进是正常的，没有问题

**Comment by dev-emmon** [comment]
可以收到系统推送的群消息

**Comment by mapleflow** [comment]
先看能不能获取到群？

**Comment by dev-emmon** [comment]
是可以的，今天又试了下，可以了，也许和其它注册的消息冲突了
