### ISSUE TITLE
好友将自己拉黑后，给对方发消息会发送多条消息

### ISSUE THREAD

**Issue by mudebao** [youfou/wxpy#21]
我测试的时候，让好友把发送方拉黑，发送消息的时候，会出现多条发送日志。
连续多条日志：
至尊宝: 消息已发出，但被对方拒收了。 (Note)
最后，导致该微信号被限制：
再给其他正常好友发消息也出错：
发送消息过于频繁，等待对方接受你的好友请求后再发。 (Note)

不知道有没有什么设置？感谢！

**Comment by youfou** [comment]
能否贴出代码看看？
一般出现这种情况24小时后会解封的，平时也尽量使用小号进行测试。

**Comment by mudebao** [comment]
你好，感谢回复！我发现是由于我注册了自动回复消息的功能，循环发消息了，导致发消息频繁了。自己挖的坑！

**Comment by youfou** [comment]
能找到问题就好哈
