### ISSUE TITLE
如何能回复`分享网页`类型的消息

### ISSUE THREAD

**Issue by zhyc9de** [youfou/wxpy#211]
看文档里是说调用[Message.chat.send_raw_msg(...)](http://wxpy.readthedocs.io/zh/latest/chats.html#wxpy.Chat.send_raw_msg)

有人能举个例子么，如何回复

**Comment by mapleflow** [comment]
判断消息类型，然后回复。

**Comment by liguobao** [comment]
我倒是在找怎么发送Sharing类型的消息...

**Comment by gitzhou** [comment]
> 看文档里是说调用[Message.chat.send_raw_msg(...)](http://wxpy.readthedocs.io/zh/latest/chats.html#wxpy.Chat.send_raw_msg)
> 
> 有人能举个例子么，如何回复

老哥解决了么…
#166

**Comment by caynne** [comment]
> 

> 我倒是在找怎么发送Sharing类型的消息...

老哥知道怎么发送sharing类型的消息吗
