### ISSUE TITLE
Sharing消息无法获取到url

### ISSUE THREAD

**Issue by brucewzp** [youfou/wxpy#214]
Sharing 信息无法获取到url  

Python 2.7  

wxpy (0.3.9.8)  
![image](https://user-images.githubusercontent.com/7270576/31852529-c57d589a-b63e-11e7-990e-76bd5e5e95af.png)

**Comment by HONKONE** [comment]
你改源码把，把message里面的import html那里直接删了，不用那个，不知道为啥html的库里没有unescape

**Comment by brucewzp** [comment]
已经改了。。。anyway，只能这样了 @HONKONE

**Comment by brucewzp** [comment]
@HONKONE
