### ISSUE TITLE
Can wxpy get context conversation?

### ISSUE THREAD

**Issue by demostars** [youfou/wxpy#22]
您好~

wxpy可以获取响应上下消息么？

因为 一般的注册事件都是单句响应，图灵的上下文响应是通过特殊的uid实现的。

那么但就微信消息本身，能否做到呢？

比如

User - 用户
Bot - wxpy 程序

User: 下载xxx.mp4
                                           `下载完成是否上传？ Bot`
User:上传
                                         `上传完成，地址是:xxx Bot`

如何实现这样的注册事件呢？现在的情况似乎无法实现，我尝试了一下。

再次感谢~

**Comment by youfou** [comment]
可以通过 聊天对象的 .user_name 属性来辨别会话
wxpy.Tuling 内也是通过这种方式

**Comment by demostars** [comment]
@youfou 嗯，我的解决办法是，自己定义一个外部变量用来暂存某个用户最近一条消息，然后做判断和更新。

感谢回复~

**Comment by youfou** [comment]
也可以直接通过内置的 bot.message 来查找
```python
this_sender = msg.sender
sender_history = bot.messages.search(sender=this_sender)
```
