### ISSUE TITLE
除了开小号之外还有什么方法可以让工具接收到自己手机发送的消息

### ISSUE THREAD

**Issue by luchuanhua** [youfou/wxpy#220]
如题，现在的工具在响应别人的消息的时候工作的不错，也可以发消息到我的手机端，但是却收不到手机端发送的消息（尝试过加自己好友，使用文件传输助手等方法）。我想知道，有没有什么方法可以让工具收到我手机端发送的消息（开小号的方法我是知道的，能不能用同一个账号呢）。谢谢。

**Comment by mapleflow** [comment]
http://wxpy.readthedocs.io/zh/latest/messages.html#wxpy.Bot.register

except_self – 排除由自己发送的消息

**Comment by luchuanhua** [comment]
谢谢mapleflow，可以处理自己发送的消息了。
PS. 用函数之前没有好好看参数列表，犯了这个错
