### ISSUE TITLE
邀请入群

### ISSUE THREAD

**Issue by 491637568** [youfou/wxpy#23]
为什么没办法使用group的add_members和remove_members方法了。。里面username传微信昵称和微信号都不行。

**Comment by youfou** [comment]
需要传入单个用户对象，或用户对象的列表。而不是昵称或微信号。

**Comment by youfou** [comment]
举个例子
```python
my_friend = ensure_one(bot.search('某个人的名字'))
my_group.add_members(my_friend)
```

**Comment by 491637568** [comment]
非常感谢您这么及时的解答，已解决。
我是当时看您在知乎https://pic4.zhimg.com/v2-2043a6c577c2dc2ff92d49456ff15fc7_b.png里写的是user_name才导致理解错误，不知道是不是有问题

**Comment by 491637568** [comment]
不好意思，想当然了~试了一下，是图中作者的问题。
顺便再问一下，用这个扫码登录后选择cache_path=True。然后使用embed阻塞，是不是只要电脑不关，就可以一直保活。微信那边有超时session过期的说法吗

**Comment by youfou** [comment]
目前看，掉线通常与网络稳定性和机器人行为有关。
有些行为异常的可能会被踢下线。
我这边至少24小时没问题，没有试过很久的，因为经常更新代码重启测试。
