### ISSUE TITLE
new-core 分支里的 set _remark_name 不能修改备注名

### ISSUE THREAD

**Issue by chenbotao828** [youfou/wxpy#244]
如题，new-core 分支里的 set _remark_name 不能修改备注名，现在是手机码字，好像记得 friend.set_remark_name(“xxx”) 返回一个 error response，备注名没有被成功修改。请我这个bug如何解决，谢谢🙏

**Comment by mapleflow** [comment]
是不是被限制了，备注名修改每天有次数限制？

**Comment by chenbotao828** [comment]
@youfou 传参数的时候没有标明参数，最后一行 加上 `remark_name=` 修改后：

    def set_remark_name(self, remark_name):
        """
        设置或修改好友的备注名称

        :param remark_name: 新的备注名称
        """

        logger.info('setting remark name for {}: {}'.format(self, remark_name))

        return self.core.op_log(self, 2, remark_name=remark_name or '')
