### ISSUE TITLE
如何获取群二维码？

### ISSUE THREAD

**Issue by zbing3** [youfou/wxpy#25]
请问如何获取群二维码？我查看了 Group 对象的所以方法 并没有关于二维码的。谢谢！

**Comment by youfou** [comment]
Web微信没有分享群聊二维码的功能。
你可以采用邀请好友加入的方式，或者像 wxpy 交流群那样，采用机器人托管:
https://gist.github.com/youfou/03c1e0204ac092f873730f51671ce0a8
