### ISSUE TITLE
【建议】能不能支持小冰啊？

### ISSUE THREAD

**Issue by Levstyle** [youfou/wxpy#26]
小冰是个公众号，支持自动回复图片，声音，文字，所以我就想啊，能不能把非小冰发给我的消息全部自动发给小冰，然后提取小冰的回复，回复给非小冰对象，难点就是：有时候，你说一句，小冰有时要回复多句，而且不能分辨小冰的回复到底是回复哪一句的。。。不知道大神有没有法？

**Comment by youfou** [comment]
转发消息可以使用 wxpy 内置的转发功能:
http://wxpy.readthedocs.io/zh/latest/messages.html#wxpy.Message.forward

对于消息关联的问题，可以把小冰当作资源来使用
1. 注册小冰的消息，收到的消息加入到队列（Queue）
2. 队列的另一端，在处理消息时，需要设定两个阈值：有效连续时间、回复超时

其中有效连续时间，表示获取到一条回复后，队列内 N 秒内又出现了新消息，但无人认领（没有其他人发起请求），则作为最后一个请求的回复；而回复超时，则表示一条请求后，N 秒内没有回复，则表示无回复（各种原因）。

不过即便按照上面的方式执行，“上下文关联”的问题，仍然是无解的。
比如问小冰“我上句话说了啥”，小冰可能回复其他人说的话。

**Comment by Levstyle** [comment]
谢谢大佬！  ^_^
