### ISSUE TITLE
请问如何填加多个好友，同时发送信息？？

### ISSUE THREAD

**Issue by zhanghdong** [youfou/wxpy#29]
my_friend = robot.friends().search('游否', sex=MALE, city="深圳")[0]
robot.my_friend.send('Hello WeChat!')

此代码只能给一个好友发送信息，请问有什么方法，可以填加2个以上的好友，同时发送？？

**Comment by youfou** [comment]
只有两种方式

1. 遍历多个好友，逐个发送
2. 建立群聊，在群中发送
