### ISSUE TITLE
群members search过滤后调用add_all方法提示参数个数不对

### ISSUE THREAD

**Issue by ideago** [youfou/wxpy#3]
如标题截图两张如下

![2](https://cloud.githubusercontent.com/assets/7457605/23544471/2331f414-0032-11e7-89a6-4be72d64961d.png)
![Uploading 3.png…]()

**Comment by youfou** [comment]
已修复，请安装GitHub上的最新版本 v0.1.1 进行验证:

```shell
pip3 install -U git+https://github.com/youfou/wxpy
```
