### ISSUE TITLE
报错 OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by hillerliao** [youfou/wxpy#32]
"""
In [1]: ---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/root/pyprj/wxbot_pya/run.py in <module>()
    111     pos_send()
    112     complex_reply()
--> 113     embed()

/root/.virtualenvs/wxpy_bot/lib/python3.5/site-packages/wxpy/utils/console.py in embed(local, banner, shell)
     64     for _shell in shell, _ipython, _bpython, _python:
     65         try:
---> 66             _shell(local=local, banner=banner)
     67         except (TypeError, ImportError):
     68             continue

/root/.virtualenvs/wxpy_bot/lib/python3.5/site-packages/wxpy/utils/console.py in _ipython(local, banner)
     12         config=load_default_config()
     13     )
---> 14     shell()
     15 
     16 

/root/.virtualenvs/wxpy_bot/lib/python3.5/site-packages/IPython/terminal/embed.py in __call__(self, header, local_ns, module, dummy, stack_depth, global_ns, compile_flags, **kw)
    226         # our call and get the original caller's namespaces.
    227         self.mainloop(local_ns, module, stack_depth=stack_depth,
--> 228                       global_ns=global_ns, compile_flags=compile_flags)
    229 
    230         self.banner2 = self.old_banner2

/root/.virtualenvs/wxpy_bot/lib/python3.5/site-packages/IPython/terminal/embed.py in mainloop(self, local_ns, module, stack_depth, display_banner, global_ns, compile_flags)
    321 
    322         with self.builtin_trap, self.display_trap:
--> 323             self.interact()
    324 
    325         # now, purge out the local namespace of IPython's hidden variables.

/root/.virtualenvs/wxpy_bot/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py in interact(self, display_banner)
    467 
    468             try:
--> 469                 code = self.prompt_for_code()
    470             except EOFError:
    471                 if (not self.confirm_exit) \

/root/.virtualenvs/wxpy_bot/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py in prompt()
    222             # This is very limited, and only accepts a single line.
    223             def prompt():
--> 224                 return cast_unicode_py2(input('In [%d]: ' % self.execution_count))
    225             self.prompt_for_code = prompt
    226             return

/root/.virtualenvs/wxpy_bot/lib/python3.5/site-packages/IPython/utils/py3compat.py in input(prompt)
    150     # to forward requests to a frontend.
    151     def input(prompt=''):
--> 152         return builtin_mod.input(prompt)
    153 
    154     builtin_mod_name = "builtins"

OSError: [Errno 9] Bad file descriptor
"""

**Comment by youfou** [comment]
看上去似乎是 embed() 和 virtualenv 之间的兼容性问题？
试试把最后那句 embed() 改为 bot.join() 看看？

**Comment by youfou** [comment]
10天无反馈，先关闭了
如果有情况，请再打开

**Comment by vinci7** [comment]
同样的问题，换上bot.join()后生效，感谢 @youfou
