### ISSUE TITLE
KeyError: 'pass_ticket'

### ISSUE THREAD

**Issue by chobijaeyu** [youfou/wxpy#340]
bot = Bot()
  File "/usr/local/lib/python3.7/site-packages/wxpy/api/bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "/usr/local/lib/python3.7/site-packages/itchat/components/register.py", line 35, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/lib/python3.7/site-packages/itchat/components/login.py", line 66, in login
    self.show_mobile_login()
  File "/usr/local/lib/python3.7/site-packages/itchat/components/login.py", line 212, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'

**Comment by jiangf13** [comment]
Same problem

**Comment by limbo-envoy** [comment]
这个问题解决了吗？登录就登录不上去怎么玩？

**Comment by chobijaeyu** [comment]
@limbo-envoy 没法解决，这个是腾讯的问题。腾讯封了我们的web登录。我的小号已经新注册的号都登录不了web版，因此也用不了这个库了。

**Comment by limbo-envoy** [comment]
> @limbo-envoy 没法解决，这个是腾讯的问题。腾讯封了我们的web登录。我的小号已经新注册的号都登录不了web版，因此也用不了这个库了。

好的，谢谢告知，可惜了还没尝试就用不了了。不过我怎么看其他人还在用的样子，我看最近的问题分支是在五天前，看样子好像登录上去了啊？

**Comment by chobijaeyu** [comment]
@limbo-envoy 我是说 小号 以及新注册的账号用不了。用能登录web版的号当然也能用啊。

**Comment by 51bitquant** [comment]
老号可以，新的微信好用不了。

**Comment by Victer-python** [comment]
老号可以，12月注册新的微信用不了。

**Comment by GlamyX** [comment]
现在老账号也不能登陆了

**Comment by Forkeep** [comment]
现在为什么新号老号都不能用了

**Comment by RexHuang** [comment]
有的老号还是可以玩，我的就可以

**Comment by 51bitquant** [comment]
用不了就用阿里的钉钉吧，干啥飞得一直用腾讯？ telegram等也挺好的。
