### ISSUE TITLE
无法建群

### ISSUE THREAD

**Issue by skyxv** [youfou/wxpy#351]
`a= bot.friends().search('a', sex=FEMALE)[0]`  
`b = bot.friends().search('b', sex=MALE)[0]`   
`friends = [xl, jm]`

两位好友正常获取到了，但是下面建群报了异常。

`first_group = bot.create_group(users=friends, topic="测试1")`

异常如下：
 ` File "python3.5/site-packages/wxpy/utils/misc.py", line 53, in check_response_body`
   ` raise ResponseError(err_code=err_code, err_msg=err_msg)`
`wxpy.exceptions.ResponseError: err_code: -1000; err_msg: 返回值不带BaseResponse`

**Comment by danta666** [comment]
微信官方封掉了

**Comment by ztt0tian** [comment]
我也遇到了  有没有别的方案实现之一功能呀
