### ISSUE TITLE
how to use wxid to add friends

### ISSUE THREAD

**Issue by riddle911** [youfou/wxpy#36]
hi 
老哥， 看到你commit了一个新功能，是add friend by wxid
请问一下 这个是怎么用呢。貌似没有文档出来.......

**Comment by youfou** [comment]
文档也分开发分支的哈，请看这里
http://wxpy.readthedocs.io/zh/develop/bot.html#id5
直接用 .add_friend() 就可以了，第一个参数支持多种类型

**Comment by riddle911** [comment]
嗯嗯 已经看到了。刚跑了一下。貌似没成功。
老哥另外 还问一下，您写的这个功能是用wxid那一长串还是个人可以自定义的微信ID

**Comment by youfou** [comment]
个人定义的微信ID是支持的，另一种 wxid_xxxx 这种没试过
可以发报错信息看下。

**Comment by riddle911** [comment]
收到了~谢谢老大哈。
跑了一下还是有问题...我再研究一下哈 应该是小白问题。
