### ISSUE TITLE
请问一下，有撤回消息的接口吗

### ISSUE THREAD

**Issue by Chen-kaiyuan** [youfou/wxpy#361]
请问一下，有撤回消息的接口吗

**Comment by 2276959997** [comment]
message种的 recall()
https://wxpy.readthedocs.io/zh/latest/messages.html#wxpy.SentMessage.recall

**Comment by huanyue6660** [comment]
你看我写的博客：https://blog.csdn.net/huanyue6660/article/details/79583851

**Comment by Chen-kaiyuan** [comment]
@2276959997 ，@huanyue6660 谢谢大家，已经解决问题
