### ISSUE TITLE
是否可以做成基于PC端的微信机器人，有没有兴趣一起研究下？

### ISSUE THREAD

**Issue by taylorshuang** [youfou/wxpy#374]
微信已经对web登陆做了限制，新的用户已经无法登陆微信。我试用了wetool这个工具，感觉很牛，有没有可能基于这个做个开源的实现，大伙出出注意，或者提供一些思路，我来实现，然后承诺开源出来

**Comment by taylorshuang** [comment]
有没有人出出主意呢？

**Comment by xflyyxfl** [comment]
基于这个，我已经做成过机器人了，机器人连接的是小冰~

**Comment by taylorshuang** [comment]
> 基于这个，我已经做成过机器人了，机器人连接的是小冰~

可以给我试用下不？

**Comment by taylorshuang** [comment]
> 基于这个，我已经做成过机器人了，机器人连接的是小冰~

或者讲讲原理是什么，怎么做哈，没有看到开源的

**Comment by xflyyxfl** [comment]
你先把游否的这个封装好的工具能用上再说吧，连上机器人是第二步。如果你是因为新注册的用户不能使用web微信而不能使用这个pywx登录，那么你应该先去找个可以登录的微信号

**Comment by hfcheng66** [comment]
youfou是基于itchat的，而且youfou没有用最新的itchat。
itchat是基于web微信，功能有限制，最不爽的是不能长久在线，经常莫名其妙就断线了，需要扫描重新登录。 有没有解决办法？

**Comment by xflyyxfl** [comment]
我做成的微信机器人，wechat号 xulei263458
你可以添加好友试着跟他聊一下。
技术原理是基于youfou封装的itchat。当然微信现在是封了很多接口，不能用了。这个是因为web微信的限制，只要是基于web微信的是没有办法的

**Comment by hfcheng66** [comment]
@xflyyxfl , 多谢。 能否说一下你的运行环境？ 这个机器人可以长时间在线吗？ 需要什么特别的设置吗？ 我用itchat，现在最长在线时间是3、4天。

**Comment by yuxingxing1988** [comment]
@taylorshuang  大佬你找到思路没？

**Comment by xflyyxfl** [comment]
@hfcheng66 还是你厉害，我这个也是经常断（经常是因为触发了一些bug，我自己改了一些封装里面的东西，后面的一些bug我没有再继续改了），做了监控，断了后会重启过程，手机上点下确认就好了，所以不是特别困扰。

**Comment by xflyyxfl** [comment]
最长在线时间2天无bug触发没断线，莫明其妙断线的我还没有遇到过

**Comment by yooongchun** [comment]
> 微信已经对web登陆做了限制，新的用户已经无法登陆微信。我试用了wetool这个工具，感觉很牛，有没有可能基于这个做个开源的实现，大伙出出注意，或者提供一些思路，我来实现，然后承诺开源出来

这里有个关于wetool实现原理的简单介绍喔：https://zhuanlan.zhihu.com/p/73983958
期待大佬做出开源方案~

**Comment by taylorshuang** [comment]
我没有找到思路，基于web的方式肯定不行，不稳定，且不能支持新的微信账号，基于pc的微信是可以的，且现在市场上有现成的产品---wetool，我试用了，蛮好用

**Comment by taylorshuang** [comment]
> > 微信已经对web登陆做了限制，新的用户已经无法登陆微信。我试用了wetool这个工具，感觉很牛，有没有可能基于这个做个开源的实现，大伙出出注意，或者提供一些思路，我来实现，然后承诺开源出来
> 
> 这里有个关于wetool实现原理的简单介绍喔：https://zhuanlan.zhihu.com/p/73983958
> 期待大佬做出开源方案~

就是这个思路，基于这个可以做出来的
