### ISSUE TITLE
有办法发送语音吗

### ISSUE THREAD

**Issue by RyanKung** [youfou/wxpy#38]
大概需求就是把本地的音频，当作语音发出去？

**Comment by youfou** [comment]
这个无解…Web微信无法发送语音，所以只能作为文件发出
不过可以考虑转换成视频发出去（播放时还是一键的，相比文件方便点）

**Comment by RyanKung** [comment]
感觉麻烦的地方就是把音频格式转换成amr对吧

**Comment by RyanKung** [comment]
我看了一下接收到的语音消息的格式，不知道能不能通过构造raw_msg的方式发出去。接收到的语音消息其实就是amr格式对吧。

**Comment by youfou** [comment]
现在主要的问题是，并不清楚Web微信有没有留下这样的冗余接口，如果有的话，也不清楚接口是怎样的。不过仍然可以摸索。
