### ISSUE TITLE
公众号类消息只能获得多图文的头条内容

### ISSUE THREAD

**Issue by earlzhang** [youfou/wxpy#39]
目前对于公众号类消息可以用Sharing来捕获，但是似乎仅限于单图文的。

如果对方发布的是多图文格式的，只能获得第一条的所有信息，而第二条及随后的所有信息全部被忽略。

不知道能否将多图文的信息转变为一个列表，这样可以逐一查看各自的内容。

**Comment by youfou** [comment]
感谢反馈，这个问题我先前没有注意到。
我看下如何重现(好像只能被动收到)，然后看收到的数据中是否包含了后几条信息。

**Comment by earlzhang** [comment]
我因为自己有公众号，是通过用公众号给测试的帐号发送预览的方式来重现的。您如果没微信公号，我可以配合你重现下。

**Comment by stirb520** [comment]
我测试了下，ichat原始数据是包含所有链接的，可能你的代码只是获取了第一条链接。

**Comment by Jehho** [comment]
请问想要把几篇文章都获取到，这个问题现在有什么办法可以解决吗

**Comment by youfou** [comment]
已在最新版本 (0.3.9.7) 中加入支持，文档:
http://wxpy.readthedocs.io/zh/latest/messages.html#wxpy.Message.articles
