### ISSUE TITLE
总是提示groups()没有search()方法

### ISSUE THREAD

**Issue by makingworld** [youfou/wxpy#4]
groupWolf = robot.groups().search('狼群')[0]
robot.register(groupWolf)
到这总会报错，提示没有search方法，改成如下：
`print(robot.groups())`
输出结果为[]。
改成
`robot.register()
print(robot.groups())
`
才会有内容，求修复啊

**Comment by youfou** [comment]
出现没有 search 方法，是因为 groups() 返回了空列表，之后没有转化为Groups对象，已修复。
----
建议试试在 groups() 方法内增加 update=True 参数，看看能不能找到你要的群。
有些不活跃的群，也有可能不被返回，这种情况下，试试先把群"保存到通讯录"(群设置)。
