### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by bestony** [youfou/wxpy#43]
Sharing 信息无法获取到url

Python 3.6.1

wxpy (0.3.9.2)

<img width="671" alt="wx20170430-015621 2x" src="https://cloud.githubusercontent.com/assets/13283837/25557644/3e980390-2d48-11e7-96f3-c94c755640c2.png">

报错位置 https://github.com/bestony/wxpy/blob/master/wxpy/api/messages/message.py#L199

**Comment by youfou** [comment]
感谢反馈，问题已修复。

请安装 0.3.9.3 版本
```shell
pip3 install wxpy -U
```
