### ISSUE TITLE
改的过分了，以前的代码全失效了。

### ISSUE THREAD

**Issue by MukuroSama** [youfou/wxpy#48]
都不知道怎么修

**Comment by youfou** [comment]
what... 是很久没更新了吧
可以根据 traceback 逐个修改，不会很多的

**Comment by MukuroSama** [comment]
不记得开始用的哪个版本了，可能之前无意中就更新过，因为最近发现所有的print的不显示了。刚一口气更新到最新，彻底炸了，不会玩了。
哪里有每个版本的改动？github的releases页面只能看到0.2.5。
readthedocs上我都不知道怎么看历史版本。

**Comment by youfou** [comment]
Releases 里有 10 个版本呢，重要改动都有注明“重要”
https://github.com/youfou/wxpy/releases
