### ISSUE TITLE
创建群组出错

### ISSUE THREAD

**Issue by powersam** [youfou/wxpy#49]
from wxpy import *
bot=Bot()
bot.create_group(['ken06o',],'hello')
-------------------------------------------错误代码----------------------------------------------
Traceback (most recent call last):
  File "D:/app/math/add_friend.py", line 3, in <module>
    bot.create_group(['ken06o',],'hello')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\wxpy\api\bot.py", line 365, in create_group
    raise Exception('Failed to create group:\n{}'.format(pformat(ret)))
Exception: Failed to create group:
{'BaseResponse': {'ErrMsg': '请求成功',
                  'RawMsg': '<e>\n'
                            '<ShowType>1</ShowType>\n'
                            '<Content><![CDATA[å\x88\x9bå»ºç¾¤è\x81\x8aå¤±è´¥]]></Content>\n'
                            '<Url><![CDATA[]]></Url>\n'
                            '<DispSec>30</DispSec>\n'
                            '<Title><![CDATA[]]></Title>\n'
                            '<Action>4</Action>\n'
                            '<DelayConnSec>0</DelayConnSec>\n'
                            '<Countdown>0</Countdown>\n'
                            '<Ok><![CDATA[]]></Ok>\n'
                            '<Cancel><![CDATA[]]></Cancel>\n'
                            '</e>\n',
                  'Ret': 0},
 'BlackList': '',
 'ChatRoomName': '',
 'MemberCount': 0,
 'MemberList': [],
 'PYInitial': '',
 'QuanPin': '',
 'Topic': ''}

进程已结束,退出代码1

**Comment by youfou** [comment]
这个情况是因为请求“创建群聊”接口后，微信服务端返回内容中的错误码为0 (正常情况下表示操作成功)，但返回内容并没有提供新创建群聊的关键字段，比如 UserName。

wxpy 把这种情况认为是创建失败，原因未知。

可能是触发了微信服务端的某种限制，可以重试看看。

**Comment by youfou** [comment]
Hello, 今天又看了下你的代码，发现是因为你在创建群组时，users 参数填写了微信ID。
最近微信好像有调整，无论是发消息还是加好友，都不能再使用微信ID了，所以请使用wxpy的用户对象，或类似 '@1234567890abcdef...' 的 user_name。

**Comment by yeyuguo** [comment]
我使用了 <Friend: xxx > wxpy 的对象list 作为参数，一样的报错：
```py
users = [<Friend: xxx1 >, <Friend: xxx2 >]
bot.create_group(users,topic='weiyi')
# 报错信息如下
ResponseError: err_code: -1000; err_msg: 返回值不带BaseResponse
```

**Comment by Victer-python** [comment]
```
In [7]: users = ['糟糕，***','橘****','D***']

In [8]: bot.create_group(users, topic='test_group')

# 报错信息如下
ResponseError: err_code: -1000; err_msg: 返回值不带BaseResponse
```
