### ISSUE TITLE
接收不到机器人发给文件传输助手的消息？itchat是可以的，请问有什么办法吗？

### ISSUE THREAD

**Issue by secreter** [youfou/wxpy#59]
```
@bot.register(bot.file_helper)
def reply_file_helper(msg):
    print(msg.sender)
    print(msg.sender.puid)
    return 'received: {} ({})'.format(msg.text, msg.type)
```
我给文件传输助手单独创建函数，接收不到。
```
@bot.register()
def print_others(msg):
    print(msg)
```
然后想看看它到底在什么分类里，但打印所有接收的消息，也接收不到文件传输助手的消息。

请问是我的方法不对还是框架不支持？有可行方法吗？谢谢了~

**Comment by youfou** [comment]
消息注册时会默认忽略自己发送的消息，所以需要调整注册时的参数 `except_self` 为 `False`
文档: http://wxpy.readthedocs.io/zh/latest/messages.html#wxpy.Bot.register
