### ISSUE TITLE
robot=Robot()之后扫码登录问题

### ISSUE THREAD

**Issue by lewoer** [youfou/wxpy#6]
下载二维码后无法扫描登陆，说是微信需要升级(已经最新了)。对手机版本要求那么高吗？ @youfou

**Comment by youfou** [comment]
试试在Web微信 https://wx.qq.com/
看是否有相同的提示？

暂不清楚对手机端版本的要求呢。

**Comment by lewoer** [comment]
原话是这样:“无法识别的二维码需要将微信升级至最新版本才能识别此二维码”操作没问题啊，就是很怪，看看其他人有没有反馈吧！

**Comment by lewoer** [comment]
ooo，web微信也不可以，是我手机问题吗？

**Comment by youfou** [comment]
并不清楚，尝试升级下微信版？
