### ISSUE TITLE
如何在手机与 wxpy 之间同步「已读」状态

### ISSUE THREAD

**Issue by vvtommy** [youfou/wxpy#62]
如题。
观察到在 Web 版中，假如某条消息已读，则手机上该消息的「已读」状态会被立即同步(红点或者数字角标消失)。

**Comment by youfou** [comment]
感谢提议，已经在开发分支中实现。

自动将所有新消息标为已读:
http://wxpy.readthedocs.io/zh/develop/bot.html#wxpy.Bot.auto_mark_as_read
将单个聊天对象标为已读:
http://wxpy.readthedocs.io/zh/develop/chats.html#wxpy.Chat.mark_as_read

安装开发分支体验此功能:
pip3 install -U git+https://github.com/youfou/wxpy.git@develop
