### ISSUE TITLE
macos下用pycharm测试无法发送照片

### ISSUE THREAD

**Issue by xjkj123** [youfou/wxpy#68]
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='file.wx8.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxuploadmedia?f=json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x105e84320>: Failed to establish a new connection: [Errno 60] Operation timed out',))

返回错误

**Comment by youfou** [comment]
试试在 wx.qq.com 上面能否发送成功？
