### ISSUE TITLE
“用微信监控你的程序”还是需要扫码？

### ISSUE THREAD

**Issue by ylqfp** [youfou/wxpy#7]
如果还是需要扫码，可用性就没有那么强了啊

**Comment by youfou** [comment]
可以缓存会话的。

具体可见:
http://wxpy.readthedocs.io/zh/latest/bot.html?highlight=cache_path#wxpy.Bot
http://wxpy.readthedocs.io/zh/latest/logging_with_wechat.html?highlight=cache_path#wxpy.get_wechat_logger

logging 功能仅仅是其中一项功能，wxpy 还可以用来做很多其他事情哈。

**Comment by ylqfp** [comment]
谢谢！请问缓存能保存多久呢？

**Comment by youfou** [comment]
并不久哈，取决于微信对"无心跳会话保留时长"的策略，个人测试在5~20分钟左右。

**Comment by ylqfp** [comment]
那就没办法做实时监控了= =
简单起见，近似成1个小时处理一次的话，对这种定时类任务，或许可以start起来，在程序里面定时调函数？

**Comment by ylqfp** [comment]
start运行起来后，应该不用再扫码了吧

**Comment by youfou** [comment]
嗯，这样也是可以的，把机器人当作一个长期运行的服务，从外部调用。
