### ISSUE TITLE
好友请求api

### ISSUE THREAD

**Issue by wanggaolin** [youfou/wxpy#79]
我看了你的代码也没有找到接受新的好友请求api,能告诉下吗?

**Comment by youfou** [comment]
http://wxpy.readthedocs.io/zh/latest/bot.html#wxpy.Bot.accept_friend

**Comment by wanggaolin** [comment]
谢谢你的回答
那么它原生的接口是哪个?比如:https://wx2.qq.com/cgi-bin/mmwebwx-bin/
咱们有交流群吗?

**Comment by youfou** [comment]
wxpy 主要关注的是 Python 接口，对于 Web 协议并没有太多关心。

Web 层主要是通过 itchat 来实现的。
加好友和接收好友是同个接口，不同参数。

请见 itchat 的源码 (`add_friend`):
https://github.com/littlecodersh/ItChat/blob/master/itchat/components/contact.py#L354

wxpy 有交流群，可以扫码加项目主页的机器人来获取群入口。

**Comment by wanggaolin** [comment]
恩,谢谢!
