### ISSUE TITLE
如何注册多个函数分别对应不同的群

### ISSUE THREAD

**Issue by davieds** [youfou/wxpy#85]
看了你的例子，发现可以分别注册不同的函数，对应不同的群做出相应的处理
我尝试在代码中注册了多个函数，可是只是响应最后一个注册的函数，请问需要怎么更改呢。

@robotinfo.register(KeyWordRepliesGroup, TEXT)
    .......

@robotinfo.register(GroupTuling, TEXT)
   .......

**Comment by davieds** [comment]
这个是作者的例子：
# 在其他群中回复被 @ 的消息
@bot.register(Group, TEXT)
def reply_other_group(msg):
    if msg.chat not in groups and msg.is_at:
        if supported_msg_type(msg, reply_unsupported=True):
            tuling.do_reply(msg)


# wxpy 群的消息处理
@bot.register(groups, TEXT, except_self=False)
def wxpy_group(msg):
    kick_msg = remote_kick(msg)
    if kick_msg:
        return kick_msg
    elif msg.text.lower().strip() in ('帮助', '说明', '规则', 'help', 'rule', 'rules'):
        return help_info
    elif msg.is_at:
        return 'oops…\n本群禁止使用机器人[撇嘴]\n想我就私聊呗[害羞]'


@bot.register(test_group)
def forward_test_msg(msg):
    if msg.type is TEXT:
        ret = wxpy_group(msg)
        if ret:
            return ret
        elif msg.text == 'text':
            return 'Hello!'
        elif msg.text == 'at':
            return 'Hello @{} !'.format(msg.member.name)

**Comment by youfou** [comment]
wxpy 会根据已注册的配置(也就是各 @bot.register(...))，倒序按消息所在的聊天对象和消息类型，来查找需要使用的响应函数。
一旦找到合适的响应函数，就会直接使用，而不再继续查找，也就是说，只匹配一次。

所以要为不同的群注册不同的函数，只要注册时的 chats 参数配置为不同的群即可。

**Comment by davieds** [comment]
作者：就是说 groups 内不包含 test_group
不过看了下，包含也没事，但如果是test_group 的消息，只会用调戏那个函数来回复，回复那个函数不会被用到

Question：
我现在的回复的那个函数不会响应，目的是想要注册的群有响应的操作，作者能否提供个案例呢。不知如何更改 😂️😂️

**Comment by youfou** [comment]
可以这样，把 logging level 调到 DEBUG，这样可以从日志中看到每条消息匹配了什么函数

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

日志中的 “(func: xxx)“ 表示匹配的函数，如果为 None 的话，表示没有匹配

**Comment by davieds** [comment]
在日志中能看到注册了群的函数，消息有显示(func: xxx)，但都是只匹配最后一个
其他注册了的函数的群，都不响应，有什么方法吗

**Comment by youfou** [comment]
方便发代码处理看下？包括每个注册中 `chats` 参数的定义。
比如 KeyWordRepliesGroup 和 GroupTuling 是怎么定义的

**Comment by davieds** [comment]
KeyWordRepliesGroup = []
GroupTuling = []

dic = {"isOpenGroupTuling":"1","isGroupReply":"1","groupPuid":["210eceb6",a979afac1]}

for dic in groupManager:
        #获取群
        groupPuid = dic['groupPuid']
        if len(robotinfo.groups().search(puid=groupPuid)) !=0:
            group = robotinfo.groups().search(puid=groupPuid)[0]
            if dic['isOpenGroupTuling'] =='1':
                GroupTuling.append(group)
            if dic['isGroupReply'] == '1':
                KeyWordRepliesGroup.append(group)

@robotinfo.register(KeyWordRepliesGroup, TEXT)
    def groupKeywordReplies(msg):
        group = msg.chat
        for dic in groupManager:
            if dic['groupPuid'] == group.puid:
                groupkw_replies = dic['groupKeywordReplies']
                for reply, keywords in groupkw_replies.items():
                    for kw in keywords:
                        if kw in msg.text.lower():
                            logger.info('reply by keyword: \n{}: "{}"\nreplied: "{}"'.format(
                                (msg.member or msg.chat).name, msg.text, reply))
                            time.sleep(2)
                            msg.reply(reply)
                            return


    @robotinfo.register(GroupTuling, TEXT)
    def isOpenGroupTuling(msg):
        group = msg.chat
        for dic in groupManager:
            if dic['groupPuid'] == group.puid:
                if msg.is_at:  #if msg.chat not in groups and msg.is_at:
                    if supported_msg_type(msg, reply_unsupported=True):
                        time.sleep(2)
                        tuling.do_reply(msg)

**Comment by youfou** [comment]
你上面代码中一开始定义 `dic` 为一个字典
为什么后面又 `for dic in groupManager:` (for 之后 dic 又随着迭代被重新定义了) ？
那么 `groupManager` 是什么？

----

或者你可以这样:
1. 在首个 `@robotinfo.register(...)` 开始之前，调试下，看看 `KeyWordRepliesGroup` 和 `GroupTuling` 分别是什么值？
2. 检查一下，刚才提到的 “其他注册了的函数的群，都不响应” 中涉及到的群，存在于以上两个变量中的哪一个？

**Comment by davieds** [comment]
不好意思，粘贴的时候复制少了 ，groupManager 是个大字典，dic 是其中的一个小字典。

**Comment by davieds** [comment]
在首个 @robotinfo.register(...) 开始之前，调试下，看看 KeyWordRepliesGroup 和 GroupTuling 分别是什么值？
这两个值打印出来是个群list  
 KeyWordRepliesGroup： [<Group: 三人组>]
GroupTuling：[<Group: 三人组>]

检查一下，刚才提到的 “其他注册了的函数的群，都不响应” 中涉及到的群，存在于以上两个变量中的哪一个？
    KeyWordRepliesGroup 和 GroupTuling 可能包含同一个群。

**Comment by youfou** [comment]
所以从打印的两个 list 来看，只有 “三人组” 这个群被注册了，其他群则没有注册到。
而 "三人组" 这个群同时被注册在两个函数中，根据 wxpy 的匹配规则(后注册优先，只匹配一个)，只会匹配最后的 `isOpenGroupTuling `。

**Comment by davieds** [comment]
明白意思了。
那这样处理起来是不是很麻烦。
注册所有的群，在注册里面的函数做判断逻辑。。。。

**Comment by youfou** [comment]
可以按需注册的，而且可以在函数内传递 msg 给另一个响应函数。

比如你先注册个匹配所有群的 @bot.register(Group) 做一些常规操作
然后再注册个特别的，比如 @bot.register(my_special_groups) 在里面可以先做一些特别的，然后再传递给前一个注册的函数

```python

my_special_groups = bot.groups().search('wxpy')
# 会匹配多个群，类似 [group1, group2, group3...]

@bot.register(Group)
def print_all_groups(msg):
    print(msg)

@bot.register(my_spical_groups)
def reply_my_spical_groups(msg):
    # 针对这些特别群的操作
    msg.reply('received.')
    # 再传递给上面那个函数
    print_all_groups(msg)

embed()
```

**Comment by davieds** [comment]
厉害了 我的哥 。谢谢作者，我去尝试下。
