### ISSUE TITLE
Bot 参数 cache_path 是否可以自定义？

### ISSUE THREAD

**Issue by chenbotao828** [youfou/wxpy#86]
:param cache_path:
            * 设置当前会话的缓存路径，并开启缓存功能；为 `None` (默认) 则不开启缓存功能。
            * 开启缓存后可在短时间内避免重复扫码，缓存失效时会重新要求登陆。
            * 设为 `True` 时，使用默认的缓存路径 'wxpy.pkl'。

        if cache_path is True:
            cache_path = 'wxpy.pkl'

cache_path 是否可以自定义， 而不是统一默认值wxpy.pkl。
不同账号登陆就不需要删除 .pkl 文件了

**Comment by youfou** [comment]
这个参数可以填写你想要的名字，比如 'my_bot.pkl'
如果有多个机器人的话，可以在登陆每个机器人之前打印个提示，现在正在登陆哪个机器人
这样避免需要扫码时用错账号
