### ISSUE TITLE
部署到linux上，发送群组消息会把错误信息也发送到消息

### ISSUE THREAD

**Issue by zzir** [youfou/wxpy#87]
是log模块的缘故么？

会一直重复发送：
Resetting dropped connection: wx2.qq.com
connection pool if full, discarding connection: wx2.qq.com

**Comment by zzir** [comment]
`get_wechat_logger()`函数`name`参数默认为`None`。我是按照文档设置的，后来加上name参数目前没问题了，希望作者给name设置个默认值，而不是None

**Comment by youfou** [comment]
曾经想过要不要做成 `name` 为 None 时通过 inspect 的方式获取 caller 的 `__name__`
不过后来考虑到要满足不同的使用场景，还保持和 `logging.getLogger()` 一致 (`None` 则为 root logger)，这样也相对比较符合预期。
