### ISSUE TITLE
实例两个机器人必须一个一个登录

### ISSUE THREAD

**Issue by davieds** [youfou/wxpy#93]
厉害的作者你好：
       我在实例化2个机器人的步骤中，必须登录了第一个机器人，才会继续第二个机器人的登录。
       这个过程能否用多线程来更改呢，同时创建多个机器人。

**Comment by youfou** [comment]
当然可以，可以用 Python 的 ThreadPool 来实现

以下代码未经测试

```python

from multiprocessing.pool import ThreadPool
from wxpy import *

cache_paths = ['bot1.pkl', 'bot2.pkl']

with ThreadPool(workers) as pool:
    bot1, bot2 = pool.map(lambda x: Bot(x), cache_paths)
```

**Comment by davieds** [comment]
感谢作者大大。

还有问题，就是运行了几天后会无响应。看日志是logout() ,什么情况会造成退出呢。

**Comment by youfou** [comment]
被远程登出了，只能看日志
如果日志没说的话，就不好说了…

要保持长期登陆，最好在手机上也保持登陆和联网

**Comment by davieds** [comment]
在登录成功的回调里面可以拿到bot的puid吗,我想在登录成功后保存下puid

**Comment by youfou** [comment]
目前无法实现，但 new-core 分支中的新版本可以支持
